application: siliconprairietech
runtime: php55
version: 1
api_version: 1

handlers:
- url: /
  script: index.html
- url: /markers.js$
  script: markers.php
- url: /invite$
  script: invite.php
- url: /add-marker
  script: add-marker.php
  login: admin
- url: /(.*)
  script: \1
