application: silicon-prairie-tech
runtime: php55
version: 1
api_version: 1

handlers:
- url: /invite$
  script: invite.php
- url: /add-marker$
  script: add-marker.php
  login: admin
- url: /markers.js$
  script: markers.php
- url: /styles.css$
  static_files: styles.css
  upload: styles.css
- url: /(.*)
  script: index.php
