runtime: php55
api_version: 1
application: silicon-prairie-tech
version: 1
threadsafe: true

handlers:
- url: /invite$
  script: invite.php
- url: /add-marker$
  script: add-marker.php
  login: admin
- url: /markers.js$
  script: markers.php
- url: /styles.css$
  static_files: styles.css
  upload: styles.css
- url: /(.*)
  script: index.php

skip_files:
# Default (https://cloud.google.com/appengine/docs/php/config/appconfig#PHP_app_yaml_Skipping_files)
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
# Custom
- ^(.*/)?composer\..+$
- ^(.*/)?README\.md$
- ^(.*/)?.*\.sh$
